version: '3.7'
services:
  db:
    image: postgres:11.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    environment:
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db
